CREATE TABLE Bolum (
    BolumID INT PRIMARY KEY AUTO_INCREMENT,
    BolumAdi VARCHAR(100) NOT NULL
);

CREATE TABLE Ogrenci (
    OgrenciID INT PRIMARY KEY AUTO_INCREMENT,
    Ad VARCHAR(50) NOT NULL,
    Soyad VARCHAR(50) NOT NULL,
    BolumID INT NOT NULL,
    FOREIGN KEY (BolumID) REFERENCES Bolum(BolumID)
);

CREATE TABLE Ders (
    DersID INT PRIMARY KEY AUTO_INCREMENT,
    DersAdi VARCHAR(100) NOT NULL,
    Kredi INT NOT NULL
);

CREATE TABLE Ogrenci_Ders (
    OgrenciID INT NOT NULL,
    DersID INT NOT NULL,
    Donem VARCHAR(20) NOT NULL,
    PRIMARY KEY (OgrenciID, DersID),
    FOREIGN KEY (OgrenciID) REFERENCES Ogrenci(OgrenciID),
    FOREIGN KEY (DersID) REFERENCES Ders(DersID)
);
